### ISSUE TITLE
Pre-processing files

### ISSUE THREAD

**Issue by anksakhuja** [snash4/GAT2VEC#7]
Hi, 
I was going through the dataset you used for "Blog catalog". The dataset website has .mat file with four different kinds of information ( eg. Usercategory,usertag,tagnetwork,friendship).
<img width="1109" alt="Screen Shot 2019-07-11 at 8 07 34 PM" src="https://user-images.githubusercontent.com/39949784/61099823-8344b800-a418-11e9-8e99-9458f53ec9f0.png">
 The files being used by your model is _graph.adjlist for capturing graph structure and _na.adjlist for attributes of the nodes.
I couldn't find any relation between the data provided in the .mat file and the above two mentioned files which your model is using. 
Could you please explain, how did you prepare this data ?

**Comment by snash4** [comment]
Hello, 
 the 'friendship' is user to user graph. From this you will get _graph.adjlist
'usertag' is the attributes of each node. From this you have to prepare _na.adjlist. 
'usercategory' is the labels for each node (multi-label)
